### ISSUE TITLE
updateStatus ( -3 )

### ISSUE THREAD

**Issue by franglais125** [RaphaelRochet/arch-update#64]
Hi,

As you may remember, I forked your extension to have it working on Debian/Ubuntu.

I'm still trying to understand everything fully... When checking the updateStatus() input, you specifically check for "-3". However, this is exactly never the case... I saw you implemented it at some point, and then removed it from the checkUpdates function.

Is this check superfluous now, or is it something to fix?

Merci!

**Comment by RaphaelRochet** [comment]
This special number was used to put the indicator in "Checking in progress" state.

I removed it later, because it yielded issues about keeping extension state after screen lock, or when the check was canceled. Also this was causing some flicker when the number of updates is shown.

Bref, that was a bad idea !

**Comment by franglais125** [comment]
Thanks a lot for your time!
I only opened this issue in case you wanted a reminder to remove the relevant lines.
In my case, I changed the relevant lines for:
```
if ( this._upgradeProcess_sourceId )
    return;
```

which normally should do the same thing, I'll see how it goes.
Regards
